### ISSUE TITLE
[BUG] [Fabric] Some intrusive holders were not registered: [Reference{null=air}, Reference{null=air}] 

### ISSUE THREAD

**Issue by shugen002** [Gu-ZT/ChineseFestivals#3]
影响版本：`fabric-0.0.2+build.21`

表现: 

服务器无法启动，最后报错为: 

```log
[05:51:17] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Some intrusive holders were not registered: [Reference{null=Block{minecraft:air}}]
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:209) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[server.jar:0.11.2]
Caused by: java.lang.IllegalStateException: Some intrusive holders were not registered: [Reference{null=Block{minecraft:air}}]
	at net.minecraft.class_2370.method_40276(class_2370.java:364) ~[server-intermediary.jar:?]
	at net.minecraft.class_5455$class_6892.method_40332(class_5455.java:41) ~[server-intermediary.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraft.class_5455$class_6891.<init>(class_5455.java:64) ~[server-intermediary.jar:?]
	at net.minecraft.class_5455$class_7781.<init>(class_5455.java:105) ~[server-intermediary.jar:?]
	at net.minecraft.class_5455.method_40316(class_5455.java:109) ~[server-intermediary.jar:?]
	at net.minecraft.class_7780.<init>(class_7780.java:36) ~[server-intermediary.jar:?]
	at net.minecraft.class_7780.method_45929(class_7780.java:88) ~[server-intermediary.jar:?]
	at net.minecraft.class_7780.method_45930(class_7780.java:67) ~[server-intermediary.jar:?]
	at net.minecraft.class_7659.method_45139(class_7659.java:21) ~[server-intermediary.jar:?]
	at net.minecraft.class_7237.method_42098(class_7237.java:31) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.method_43612(Main.java:162) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:944) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	... 5 more
```

解决方案: 更新至 `fabric-0.0.3+build.34`

本issue仅做记录，方便后人查找，也希望作者能补充实际代码相关修复过程。

顺带一提，这类报错根据搜索结果来看，如果没有安装本模组，可以考虑重点关照新模组？

**Comment by Gu-ZT** [comment]
纯客户端模组，服务器没法启动应该是正常的
